def test_final_project_prego_e2e(final_project):
    final_project.open_url('https://prego.ua/')
    final_project.check_menu_button("Доставка", "ДОСТАВКА «НОВОЮ ПОШТОЮ»")
    final_project.check_menu_button("Оплата", "ЗАЛИШИЛИСЯ ПИТАННЯ?")
    final_project.check_menu_button("Гарантія та повернення", "ПОВЕРНЕННЯ ТОВАРУ У ВІДДІЛЕННІ «НОВОЇ ПОШТИ»")
    final_project.check_menu_button("Наші магазини", "Магазин чоловічого та жіночого взуття")
    final_project.check_menu_button("Блог", "Скільки пар взуття потрібно жінці для щастя")
    final_project.go_to_blog("Візьміть цю геніальну відповідь собі за девіз — і гайда шопитися!")
    final_project.shoes_catalog()
    final_project.filter_result()
    final_project.open_page_shoes()
    final_project.photo_owerview()
    final_project.add_to_cart()
    final_project.view_cart()
    final_project.open_recommended_product()
    final_project.open_action_page()
    final_project.check_bonus()